version: "3.8"
services:
  haskell-ide:
    image: haskell-ide:latest

    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
        window: 60s

    configs:
      - source: init_vim_dist
        target: /home/hsdev/.config/nvim/init.vim.dist
        uid: '1000'
        gid: '1000'
        mode: 0644
      - source: plugins_vim_dist
        target: /home/hsdev/.config/nvim/plugins.vim.dist
        uid: '1000'
        gid: '1000'
        mode: 0644
      - source: coc_settings_json_dist
        target: /home/hsdev/.config/nvim/coc-settings.json.dist
        uid: '1000'
        gid: '1000'
        mode: 0644
      - source: screenrc
        target: /home/hsdev/.screenrc
        uid: '1000'
        gid: '1000'
        mode: 0644
      - source: gitconfig_dist
        target: /home/hsdev/.gitconfig.dist
        uid: '1000'
        gid: '1000'
        mode: 0644
      - source: stack_config_yaml_dist
        target: /home/hsdev/.stack/config.yaml.dist
        uid: '1000'
        gid: '1000'
        mode: 0644

    secrets:
      - source: haskell-ide_ssh_public_key
        target: /home/hsdev/.ssh/id_rsa.pub
        uid: '1000'
        gid: '1000'
        mode: 0400
      - source: haskell-ide_ssh_secret_key
        target: /home/hsdev/.ssh/id_rsa
        uid: '1000'
        gid: '1000'
        mode: 0400

    volumes:
      - data:/home/hsdev/data
      - nvim_plugged:/home/hsdev/.local/share/nvim/plugged
      - type: bind
        source: "${SYNCED_HOST_DIR}"
        target: /home/hsdev/host

configs:
  init_vim_dist:
    file: ./init.vim.dist
  plugins_vim_dist:
    file: ./plugins.vim.dist
  coc_settings_json_dist:
    file: ./coc-settings.json.dist
  screenrc:
    file: ./.screenrc
  gitconfig_dist:
    file: ./.gitconfig.dist
  stack_config_yaml_dist:
    file: ./config.yaml.dist
  
secrets:
  haskell-ide_ssh_public_key:
    external: true
  haskell-ide_ssh_secret_key:
    external: true

volumes:
  data :
  nvim_plugged :
